import { GameElement } from "./types";

export const INITIAL_WORLD_STATE: GameElement = {
  id: "world-root",
  type: "世界",
  name: "世界",
  icon: "globe",
  enabled: false,
  visible: true,
  children: [
    {
      id: "loc-dungeon",
      type: "地点",
      name: "潮湿的地牢",
      icon: "castle",
      enabled: true,
      visible: true,
      children: [
        {
          id: "player-1",
          type: "角色",
          name: "玩家",
          icon: "user",
          enabled: true,
          visible: true,
          children: [
            {
              id: "slot-abilities",
              type: "卡槽",
              name: "能力",
              icon: "box-select",
              enabled: false,
              visible: true,
              children: [
                {
                  id: "ability-observe",
                  type: "能力",
                  name: "观察",
                  icon: "eye",
                  enabled: true,
                  visible: true,
                  children: [],
                },
                {
                  id: "ability-chat",
                  type: "能力",
                  name: "对话",
                  icon: "message-circle",
                  enabled: false, // Starts disabled
                  visible: true,
                  children: [],
                },
                {
                  id: "ability-combine",
                  type: "能力",
                  name: "合成",
                  icon: "flask-conical",
                  enabled: true,
                  visible: true,
                  children: [],
                },
                {
                  id: "ability-split",
                  type: "能力",
                  name: "拆解",
                  icon: "scissors",
                  enabled: true,
                  visible: true,
                  children: [],
                },
              ],
            },
            {
              id: "slot-inventory",
              type: "卡槽",
              name: "背包",
              icon: "backpack",
              enabled: false,
              visible: true,
              children: [
                {
                  id: "item-lint",
                  type: "物品",
                  name: "口袋里的灰尘",
                  icon: "feather",
                  enabled: true,
                  visible: true,
                  children: [],
                },
              ],
            },
            {
              id: "slot-mind",
              type: "卡槽",
              name: "意识",
              icon: "brain",
              enabled: false,
              visible: true,
              children: [],
            },
          ],
        },
        {
          id: "bldg-walls",
          type: "建筑",
          name: "石墙",
          icon: "brick-wall",
          enabled: true,
          visible: true,
          children: [],
        },
        {
          id: "bldg-gate",
          type: "建筑",
          name: "铁栅栏",
          icon: "door-closed",
          enabled: true,
          visible: true,
          children: [
            {
              id: "item-key-hidden",
              type: "物品",
              name: "生锈的钥匙",
              icon: "key",
              enabled: true,
              visible: false, // Hidden initially
              children: [],
            },
          ],
        },
        {
          id: "concept-silence",
          type: "环境",
          name: "死寂",
          icon: "cloud-fog",
          enabled: true,
          visible: true,
          children: [],
        },
      ],
    },
  ],
};
